package io.github.seonjiwon.code_combine.domain.problem.entity;

public enum ProblemTier {
    BRONZE_V, BRONZE_IV, BRONZE_III, BRONZE_II, BRONZE_I,
    SILVER_V, SILVER_IV, SILVER_III, SILVER_II, SILVER_I,
    GOLD_V, GOLD_IV, GOLD_III, GOLD_II, GOLD_I,
    PLATINUM_V, PLATINUM_IV, PLATINUM_III, PLATINUM_II, PLATINUM_I,
    DIAMOND_V, DIAMOND_IV, DIAMOND_III, DIAMOND_II, DIAMOND_I,
    RUBY_V, RUBY_IV, RUBY_III, RUBY_II, RUBY_I,
    UNRATED
}
